name: main

on:
  push:
  schedule:
    - cron: '0 11 * * *'  # todos los d√≠as a las 08:00 Fortaleza (11:00 UTC)
  workflow_dispatch:       # permite ejecutarlo manualmente desde Actions

permissions:
  contents: write   # necesario para poder hacer push a main

jobs:
  test-action-svg-only:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - name: build svg-only action
        run: |
          npm run build:action
          rm -rf svg-only/dist
          mv packages/action/dist svg-only/dist || true

      - name: generate-snake-game-from-github-contribution-grid
        id: generate-snake
        uses: ./svg-only
        with:
          github_user_name: Thiago-Taboada
          outputs: |
            dist/svg/github-contribution-grid-snake.svg
            dist/svg/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: ensure the generated file exists
        run: |
          ls -R dist/svg || true
          test -f dist/svg/github-contribution-grid-snake.svg
          test -f dist/svg/github-contribution-grid-snake-dark.svg

      - name: commit and push SVGs to main
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"

          mkdir -p dist/svg
          ls dist/svg

          git add dist/svg/*.svg
          git commit -m "CI: update generated SVGs" || echo "No SVG changes to commit"
          git push origin main
